version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_DB: crud_prueba_dav_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/postgresql/data
    networks:
      - test-network
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: prueba_dav_backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/crud_prueba_dav_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: 123456
    depends_on:
      - db
    networks:
      - test-network
    ports:
      - "8080:8080"

networks:
  test-network:
    driver: bridge

volumes:
  db_data: